<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLiCuaHangDienThoai" Class="QLDTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HALO\SQLEXPRESS;Initial Catalog=QuanLiCuaHangDienThoai;Integrated Security=True" SettingsObjectName="QuanLiCuaHangDienThoai.Properties.Settings" SettingsPropertyName="QuanLiCuaHangDienThoaiConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DANHMUC" Member="DANHMUCs">
    <Type Name="DANHMUC">
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Association Name="DANHMUC_SANPHAM" Member="SANPHAMs" ThisKey="maDM" OtherKey="maDM" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mk" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="TAIKHOAN_HOADON" Member="HOADONs" ThisKey="username" OtherKey="username" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HOADON_HOADONCHITIET" Member="HOADONCHITIETs" ThisKey="maHD" OtherKey="maHD" Type="HOADONCHITIET" />
      <Association Name="TAIKHOAN_HOADON" Member="TAIKHOAN" ThisKey="username" OtherKey="username" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONCHITIET" Member="HOADONCHITIETs">
    <Type Name="HOADONCHITIET">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HOADON_HOADONCHITIET" Member="HOADON" ThisKey="maHD" OtherKey="maHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="SANPHAM_HOADONCHITIET" Member="SANPHAM" ThisKey="maSP" OtherKey="maSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="SANPHAMs" ThisKey="maNCC" OtherKey="maNCC" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Association Name="SANPHAM_HOADONCHITIET" Member="HOADONCHITIETs" ThisKey="maSP" OtherKey="maSP" Type="HOADONCHITIET" />
      <Association Name="DANHMUC_SANPHAM" Member="DANHMUC" ThisKey="maDM" OtherKey="maDM" Type="DANHMUC" IsForeignKey="true" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="NHACUNGCAP" ThisKey="maNCC" OtherKey="maNCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.CAPNHATDM" Method="CAPNHATDM">
    <Parameter Name="maDM" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenDM" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOATK" Method="XOATK">
    <Parameter Name="usename" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAPNHATHD" Method="CAPNHATHD">
    <Parameter Name="maHD" Type="System.Int32" DbType="Int" />
    <Parameter Name="usename" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenKH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaytao" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TongTien" Parameter="tongTien" Type="System.Int32" DbType="Int" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAPNHATHDCT" Method="CAPNHATHDCT">
    <Parameter Name="maHD" Type="System.Int32" DbType="Int" />
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="soLuong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAPNHATNCC" Method="CAPNHATNCC">
    <Parameter Name="maNCC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenNCC" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAPNHATSP" Method="CAPNHATSP">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Parameter Name="hinhanh" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="soluong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maDM" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maNCC" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAPNHATTK" Method="CAPNHATTK">
    <Parameter Name="usename" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mk" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaysinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="loai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaytao" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CHECK_SP_HD" Method="CHECK_SP_HD">
    <Parameter Name="maHD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="CHECK_SP_HDResult">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DOI_PASS" Method="DOI_PASS">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DS_SP_TEN" Method="DS_SP_TEN">
    <Parameter Name="tenSP" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="DS_SP_TENResult">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.HDCTMaHD" Method="HDCTMaHD">
    <Parameter Name="maHD" Type="System.Int32" DbType="Int" />
    <ElementType Name="HDCTMaHDResult">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ID_HDCHUATHANHTOAN" Method="ID_HDCHUATHANHTOAN">
    <ElementType Name="ID_HDCHUATHANHTOANResult">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.JOIN_SP_HDCT" Method="JOIN_SP_HDCT">
    <Parameter Name="maHD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="JOIN_SP_HDCTResult">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LayDM" Method="LayDM">
    <ElementType Name="LayDMResult">
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LAYHD" Method="LAYHD">
    <ElementType Name="LAYHDResult">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LAYHDCT" Method="LAYHDCT">
    <ElementType Name="LAYHDCTResult">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LAYNCC" Method="LAYNCC">
    <ElementType Name="LAYNCCResult">
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LAYSP" Method="LAYSP">
    <ElementType Name="LAYSPResult">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LAYTK" Method="LAYTK">
    <ElementType Name="LAYTKResult">
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="mk" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThemDM" Method="ThemDM">
    <Parameter Name="maDM" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenDM" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEMHDCT" Method="THEMHDCT">
    <Parameter Name="maHD" Type="System.Int32" DbType="Int" />
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEMNCC" Method="THEMNCC">
    <Parameter Name="maNCC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenNCC" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEMSP" Method="THEMSP">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Parameter Name="hinhanh" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="soluong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maDM" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maNCC" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEMTK" Method="THEMTK">
    <Parameter Name="usename" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mk" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaysinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="loai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaytao" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TIMDM_MADM" Method="TIMDM_MADM">
    <Parameter Name="maDM" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMDM_MADMResult">
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMDM_TENDM" Method="TIMDM_TENDM">
    <Parameter Name="tenDM" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMDM_TENDMResult">
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.timHD" Method="timHD">
    <Parameter Name="maHD" Type="System.Int32" DbType="Int" />
    <ElementType Name="timHDResult">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMNCC_MANCC" Method="TIMNCC_MANCC">
    <Parameter Name="maNCC" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMNCC_MANCCResult">
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMNCC_TENNCC" Method="TIMNCC_TENNCC">
    <Parameter Name="tenNCC" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMNCC_TENNCCResult">
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMSP_MADM" Method="TIMSP_MADM">
    <Parameter Name="maDM" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMSP_MADMResult">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMSP_MANCC" Method="TIMSP_MANCC">
    <Parameter Name="maNCC" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMSP_MANCCResult">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMSP_MASP" Method="TIMSP_MASP">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMSP_MASPResult">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMSP_TEN" Method="TIMSP_TEN">
    <Parameter Name="tenSP" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMSP_TENResult">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maDM" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMTK_EMAIL" Method="TIMTK_EMAIL">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMTK_EMAILResult">
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="mk" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMTK_LOAI" Method="TIMTK_LOAI">
    <Parameter Name="loai" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMTK_LOAIResult">
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="mk" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMTK_SDT" Method="TIMTK_SDT">
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMTK_SDTResult">
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="mk" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIMTK_TK" Method="TIMTK_TK">
    <Parameter Name="useName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TIMTK_TKResult">
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="mk" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TK_DN" Method="TK_DN">
    <Parameter Name="usename" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mk" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="TK_DNResult">
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="mk" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.String" DbType="VarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.XoaDM" Method="XoaDM">
    <Parameter Name="maDM" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOAHD" Method="XOAHD">
    <Parameter Name="maHD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOAHDCT" Method="XOAHDCT">
    <Parameter Name="maHD" Type="System.Int32" DbType="Int" />
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOANCC" Method="XOANCC">
    <Parameter Name="maNCC" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOASP" Method="XOASP">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Gia_SP" Method="Gia_SP" IsComposable="true">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.TongTienHD" Method="TongTienHD" IsComposable="true">
    <Parameter Name="maHD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HinhAnh" Method="HinhAnh" IsComposable="true">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.ID_MADM_TEN" Method="ID_MADM_TEN" IsComposable="true">
    <Parameter Name="tenDM" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.ID_NCC_TEN" Method="ID_NCC_TEN" IsComposable="true">
    <Parameter Name="tenNCC" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.LOAI_TK" Method="LOAI_TK" IsComposable="true">
    <Parameter Name="usename" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mk" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.MaDM_SP" Method="MaDM_SP" IsComposable="true">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.MaNCC_SP" Method="MaNCC_SP" IsComposable="true">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.SL_SP" Method="SL_SP" IsComposable="true">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.TenSP" Method="TenSP" IsComposable="true">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.THEMHD" Method="THEMHD">
    <Parameter Name="usename" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenKH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaytao" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DOANH_THU_THEO_NGAY" Method="DOANH_THU_THEO_NGAY">
    <Parameter Name="checkIn" Type="System.DateTime" DbType="Date" />
    <Parameter Name="checkOut" Type="System.DateTime" DbType="Date" />
    <ElementType Name="DOANH_THU_THEO_NGAYResult">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(39) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Lay_Ten_DM" Method="Lay_Ten_DM" IsComposable="true">
    <Parameter Name="maDM" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.Lay_Ten_NCC" Method="Lay_Ten_NCC" IsComposable="true">
    <Parameter Name="maNCC" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.Lay_Chuoi_Byte_Hinh_Anh" Method="Lay_Chuoi_Byte_Hinh_Anh" IsComposable="true">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.String" />
  </Function>
</Database>